"""add public role and staff only courses

Revision ID: 5d2c3279fc2c
Revises: 71a7cc83a8af
Create Date: 2026-05-10 11:23:12.444400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2c3279fc2c'
down_revision: Union[str, None] = '71a7cc83a8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_staff_only', sa.Boolean(), nullable=True))
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('courses', 'is_staff_only')
    # ### end Alembic commands ###
