"""add foreign key to module.course_id

Revision ID: 71a7cc83a8af
Revises: 5518aefdb897
Create Date: 2026-05-09 18:30:13.301076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a7cc83a8af'
down_revision: Union[str, None] = '5518aefdb897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'modules', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='foreignkey')
    # ### end Alembic commands ###
